version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 65281:1972
      - 65282:52773
      - 65283:53773
    volumes:
      - ./:/irisrun/repo
