version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 1972
      - 65282:52773
      - 53773
    volumes:
      - ./:/irisrun/repo
